words = {
    'APAGADOR  DE QUADRO':	 'WANDTÅFELLÖSCHER',
    'APONTADOR':	 'BLIJGSTIFTSPIPTSER / SPITSER',
    'ARMÁRIO':	 'SPIND',
    'BLOCO DE ANOTAÇÕES':	'ANSRIJWSBLOK',
    'BOLSA  ESCOLAR': 	'SCHAULETASCH',
    'BOLSINHA':	 'BLIJGSTIFTETASCH',
    'BORRACHA':	'LÖSCHER',
    'CADEIRA': 'STAUL',
    'CADERNO': 'HEFT',
    'CADERNO DE DESENHO':	 'MÅLHEFT',
    'CANETA': 'KUUGELSRIJWER',
    'CANETINHA':	'FARWSTIFT',
    'CARTEIRA':	'SCHAULEDISCH',
    'CD': 'CD',
    'CESTA DE LIXO':	'DREKEMER',
    'CLIPE':	'PAPIJRKLAMER',
    'COLA':	'LIJM',
    'COLA COLORIDA':	 'BUNTELIJM',
    'COLA COM GLITTER':	'GLITERLIJM',
    'COMPASSO':	'CIRKEL',
    'COMPUTADOR':	 'KOMPUTATOR',
    'CORRETIVO':	 'KORREKTIV',
    'DICIONÁRIO':	'WÖÖRBAUK',
    'ESTILETE': 'STILET',
    'FITA ADESIVA':	'BAKBAND',
    'FRASE': 'SATS',
    'GIZ':	'KRIJT',
    'GIZ DE CERA':	'WASKRIJT',
    'GLOBO TERRESTRE':	'GLOBUS',
    'GRAMPO': 'KLEM',
    'GRAMPEADOR':	'KLEMMASCCHIJN',
    'LÁPIS':	 'BLIJGSTIFT',
    'LÁPIS DE COR': 'BUNTEBLIJGSTIFT / FARWBLIJGSTIFT',
    'LIVRO DE HISTÓRIA': 'GESCHICHTEBAUK',
    'LIVRO': 'BAUK',
    'LIVRO DE LEITURA':	'LEESBAUK',
    'MARCA TEXTO':	'MARKIJRSTITF',
    'PASTA': 'ORDNER',
    'PAPEL':	 'PAPIJR',
    'PERFURADOR':	'LOCHER',
    'PINCEL DE QUADRO':	'TÅFELSTIFT',
    'PRANCHETA':	'SRIJWPLANK',
    'PROVA':	'PRÖÖV',
    'QUADRO BRANCO':	'WITWANDTÅFEL',
    'QUADRO NEGRO/LOUSA':	'WANDTÅFEL',
    'RÉGUA':	 'LINJÅL',
    'RELÓGIO DE PAREDE':	 'WANDKLOK',
    'TEXTO':	'TEXT',
    'TESOURA': 'SCHËR',
    'TINTA': 'FARW / TINTE',
    'TRANSFERIDOR':	'WINKELMEETER',
    'DITADO': 'DIKTAD',
    'PROFESSOR':	'SCHAULLËRER',
    'PROFESSORA': 'SCHAULLËRESCH',
    'ALUNO': 'SCHAULEKIND',
    'CLASSE': 'KLASS',
    'RECREIO':	'PAUS',
    'GARRAFA DE ÁGUA': 'WÅTERFLASCH',
    "MOCHILA": 'SCHAULETASCH',
    "PÁTIO": "SCHAULEHOF"
}

f = []
i = 0
for v, k in words.items():
    p = {}
    i += 1
    p["PORTUGUES"] = v
    p["POMERANO"] = k,
    k = k.replace(" / ", "_") if " / " in k else k
    p["NOME_AUDIO"] = f"{i}_{k}"
    f.append(p)

print(f)
